# 服务器相关配置
server:
  servlet:
    context-path: / # 为了便于开发此处省略应用程序上下文
  port: 8201 # 为了便于开发此处使用 http 默认端口

# spring 相关配置
spring:
  application:
    name: martyr-service
  config:
    import:
      - optional:nacos:mybatis-plus-dev.yml?refreshEnabled=true
      - optional:nacos:datasource-dev.yml?refreshEnabled=true
      - optional:nacos:jwt-token.yml?refreshEnabled=true
  cloud:
    inetutils: # 抹除 Cannot determine local hostname 警告
      ignored-interfaces:
        - 'VMware Virtual Ethernet Adapter for VMnet1'
        - 'VMware Virtual Ethernet Adapter for VMnet8'
    sentinel:
      transport:
        dashboard: localhost:8858
    nacos:
      server-addr: localhost:8848